# Generated by Django 3.2.7 on 2025-03-27 09:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_posts_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='_account_user_friends_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
